sadasd

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -34,7 +34,7 @@ workflows:
       - name: Load Android SDK
         script: |
                   echo "----------------------------------------------------------------------------------"
-                  yes | /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk --licenses && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk platform-tools && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk --install "cmake;3.18.1" && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk "build-tools" && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --update || { echo 'ANDROID SDK UPDATES FAILED' ; exit 1; } 
+                  yes | /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk --licenses && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk platform-tools && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk --install "cmake;3.18.1" && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk build-tools && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --update || { echo 'ANDROID SDK UPDATES FAILED' ; exit 1; } 
                   echo "----------------------------------------------------------------------------------"
 
       - name: Run Buildozer
