adasda

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -24,7 +24,7 @@ workflows:
                   rm /Applications/Xcode-14.0.app
                   rm /Users/builder/.android/avd/emulator.avd
                   echo "----------------------------------------------------------------------------------"
-                  yes | /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses && sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk platform-tools && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk --install "cmake;3.18.1" && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --update || { echo 'ANDROID SDK UPDATES FAILED' ; exit 1; } 
+                  yes | /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk platform-tools && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/Users/builder/.buildozer/android/platform/android-sdk --install "cmake;3.18.1" && /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --update || { echo 'ANDROID SDK UPDATES FAILED' ; exit 1; } 
                   echo "----------------------------------------------------------------------------------"
                   rsync -a /usr/local/share/android-sdk/. /Users/builder/.buildozer/android/platform/android-sdk || { echo 'RSYNC FAILIURE' ; exit 1; }
                   echo "----------------------------------------------------------------------------------"
